### ISSUE TITLE
space does not shoot

### ISSUE THREAD

**Issue by dimitrilw** [LarsDu/StarRust#7]
Pressing space-bar does not seem to shoot -- at least there is no visual indication, neither a bullet going out from ship nor destruction of adversaries.

Platform: MacOS on Apple silicon chip
Browser: `Version 116.0.5845.187 (Official Build) (arm64)`

...and a screenshot of me spamming space-bar:
<img width="986" alt="image" src="https://github.com/LarsDu/StarRust/assets/5898931/834db762-79fa-4afc-9e38-0c3e50651b50">

**Comment by LarsDu** [comment]
Are you using a non-standard keyboard?

**Comment by LarsDu** [comment]
On second thought... hold _down_ the spacebar. There's a slight bug in the weapon cooldown code

**Comment by dimitrilw** [comment]
I was using the laptop's keyboard. Launching the game and holding down the spacebar does shoot. A "how to play" guide in-game (just a splash page) that mentions that requirement would be a good update. Current main menu is "Play" and "Quit" -- just add a third button that displays keyboard controls & mentions "hold down".

**Comment by LarsDu** [comment]
Ok, I haven't really worked on this since 2022 due to other priorities, and to wrap up a release of my VR (Unity) game Rogue Stargun (https://roguestargun.com)

I have a bit of downtime at the moment and went ahead and tweaked the weapon firing code so that a bullet now fires immediately on spacebar tap.

If I have more time, I'll start implementing basic things like turrets, AI, powerups, and perhaps some other things, but until then I'll hold off updates.

Continuously updating this project to keep up with bevy breaking changes is rather grueling, and I'm keeping this project in stasis until Bevy roles out an editor.

**Comment by LarsDu** [comment]
Closing b/c the issue was resolved.
